tibble(
  Endpoint = c("https://live.euroleague.net/api/Header",
               "https://live.euroleague.net/api/BoxScore",
               "https://live.euroleague.net/api/Points",
               "https://live.euroleague.net/api/Round",
               "https://live.euroleague.net/api/Players",
               "https://live.euroleague.net/api/PlayByPlay",
               "https://live.euroleague.net/api/Evolution",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v2/competitions/?/seasons/?/clubs/?",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v2/competitions/?/seasons/?/clubs/?",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v2/competitions/?/seasons/?/clubs/?/people",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v2/competitions/?/seasons/?/clubs/?/people",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v2/competitions/?/seasons/?/games",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v2/competitions/?/seasons/?/games",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v2/competitions/?/seasons/?/clubs/?/people/stats",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v2/competitions/?/seasons/?/clubs/?/people/stats",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v3/competitions/?/seasons/?/rounds/?/basicstandings",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v3/competitions/?/seasons/?/rounds/?/streaks",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v2/competitions/?/seasons/?/rounds",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v2/competitions/?/seasons/?/games",
               "https://feeds.incrowdsports.com/provider/euroleague-feeds/v2/competitions/?/seasons"
  ),
  Function = c("getGameHeader",
               "getGameBoxScore",
               "getGamePoints",
               "getGameRound",
               "getGamePlayers",
               "getGamePlayByPlay",
               "getGameEvolution",
               "getTeam_single",
               "getTeam",
               "getTeamPeople_single",
               "getTeamPeople",
               "getTeamGames_single",
               "getTeamGames",
               "getTeamStats_single",
               "getTeamStats",
               "GetCompetitionStandings",
               "GetCompetitionStreaks",
               "GetCompetitionRounds",
               "getCompetitionGames",
               "GetCompetitionHistory"
               ),
  Primitive = c(TRUE,
                TRUE,
                TRUE,
                TRUE,
                TRUE,
                TRUE,
                TRUE,
                TRUE,
                FALSE,
                TRUE,
                FALSE,
                TRUE,
                FALSE,
                TRUE,
                FALSE,
                TRUE,
                TRUE,
                TRUE,
                TRUE,
                TRUE
                ),
  Output = c("1dim tibble",
             "list of tibbles",
             "2dim tibble",
             "Character",
             "2dim tibble",
             "list of tibbles",
             "list of tibbles",
             "1dim tibble",
             "2dim tibble",
             "2dim tibble",
             "2dim tibble",
             "2dim tibble",
             "2dim tibble",
             "list of tibbles",
             "list of tibbles",
             "2dim tibble",
             "2dim tibble",
             "1dim tibble",
             "1dim tibble",
             "1dim tibble"
             )
)
